name:         kawa
version:      0.1.0.0
synopsis:     Key-value store in single files.
description:  Simple command-line tool to manage some key-value store in a single file.
category:     Database
license:      BSD3
license-file: LICENSE
author:       Thomas Feron
maintainer:   thomas.feron@redspline.com
github:       thoferon/kawa

extra-source-files:
  - README.md
  - CHANGELOG.md

ghc-options:
  - -Wall

default-extensions:
  - GeneralizedNewtypeDeriving
  - OverloadedStrings
  - TemplateHaskell

dependencies:
  - base >=4.9 && <5
  - text
  - unordered-containers

library:
  source-dirs: lib
  dependencies:
    - attoparsec
    - hashable

executables:
  kawa:
    source-dirs: src
    main: Main.hs
    dependencies:
      - directory
      - kawa
      - optparse-applicative

tests:
  unit-tests:
    source-dirs: tests
    main: Suite.hs
    ghc-options: -threaded
    dependencies:
      - kawa
      - hedgehog
